FROM plugins/base:linux-amd64

LABEL maintainer="Hou Rong <nmghr9@gmail.com>" \
  org.label-schema.name="Drone Baidu Sitemap" \
  org.label-schema.vendor="Hou Rong" \
  org.label-schema.schema-version="1.0"

RUN apk add --no-cache ca-certificates && \
  rm -rf /var/cache/apk/*

COPY release/linux/amd64/drone-baidu-sitemap /bin/
ENTRYPOINT ["/bin/drone-baidu-sitemap"]
